export const InvoiceCategory = {
  OUTGOING_PAYMENT: 'OUTGOING_PAYMENT',
  COMMERCIAL_INVOICE: 'COMMERCIAL_INVOICE',
  MISSING_QUANTITY_CLAIM: 'MISSING_QUANTITY_CLAIM',
  MISSING_QUANTITY_CLAIM_REVERSAL: 'MISSING_QUANTITY_CLAIM_REVERSAL',
  PRICE_DIFFERENCE_CLAIM: 'PRICE_DIFFERENCE_CLAIM',
  PRICE_DIFFERENCE_CLAIM_REVERSAL: 'PRICE_DIFFERENCE_CLAIM_REVERSAL',
  WHOLESALE_INVOICE: 'WHOLESALE_INVOICE',
  RETURN_INVOICE: 'VRETURN_INVOICE',
  PROVISION: 'PROVISION',
  BANK_FEE: 'BANK_FEE',
  REPAYMENT: 'REPAYMENT',
  UNCLASSIFIED: 'UNCLASSIFIED',
} as const;

export type InvoiceCategory = typeof InvoiceCategory[keyof typeof InvoiceCategory];